### ISSUE TITLE
how to train the model from previous saved checkpoints

### ISSUE THREAD

**Issue by yliuosu** [SysCV/sam-hq#74]
Hi,

Thanks for providing very detailed training commands like this.

python -m torch.distributed.launch --nproc_per_node=8 train.py --checkpoint ./pretrained_checkpoint/sam_vit_l_0b3195.pth --model-type vit_l --output work_dirs/hq_sam_l

I trained the model on my own data for 12 epoch and got a checkpoint like epoch_11.pth. If I want to train the model more from the saved checkpoint, what's command should I use? Thanks.

**Comment by ymq2017** [comment]
Hi, since the training is quick we do not implement loading saved checkpoints now. But it would be easy to achieve this. 
You could refer to loading checkpoints for evaluation in [this line](https://github.com/SysCV/sam-hq/blob/main/train/train.py#L366) and use ```--resotre_model```  argument to load checkpoint in training. Also, you could change ```--start_epoch```,```--lr_drop_epoch``` and ```--max_epoch_num``` arguments according to your own settings.

**Comment by yliuosu** [comment]
Got you. Thanks for your help and time.
